---
namespace: mahadzar81
name: yugabytedb_collection
version: 1.0.2
readme: README.md
authors:
  - mahadzar.karsof@gmail.com
description: >
  Ansible collection to deploy and manage YugabyteDB clusters on
  RHEL 8/9/10, Debian 11/12/13, and Ubuntu 22.04/24.04.
license:
  - Apache-2.0
tags:
  - yugabyte
  - yugabytedb
  - database
  - distributed
  - cluster
repository: https://github.com/mahadzar81/yugabytedb_collection
documentation: https://docs.yugabyte.com
homepage: https://www.yugabyte.com
issues: https://github.com/mahadzar81/yugabytedb_collection/issues
dependencies: {}
