---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart YugabyteDB Masters
  ansible.builtin.systemd:
    name: yugabytedb-master
    state: restarted
  when: inventory_hostname in yugabytedb_master_nodes | default(groups['yugabytedb_nodes'], true)

- name: Wait for masters to be ready
  ansible.builtin.wait_for:
    port: "{{ yugabytedb_master_ports | int }}"
    timeout: 300
    delay: 10
  when: inventory_hostname in yugabytedb_master_nodes | default(groups['yugabytedb_nodes'], true)

- name: Restart YugabyteDB Tservers
  ansible.builtin.systemd:
    name: yugabytedb-tserver
    state: restarted
  when: inventory_hostname in yugabytedb_tserver_nodes | default(groups['yugabytedb_nodes'], true)
