---
galaxy_info:
  role_name: yugabyte_install
  author: YugabyteDB Ansible Collection Contributors
  description: Downloads and installs YugabyteDB binaries
  license: Apache-2.0
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions: ["8", "9", "10"]
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions: ["jammy", "noble"]
dependencies:
  - role: yugabytedb_collection.yugabyte_preflight
