---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: yugabyte-ubuntu2404
    image: geerlingguy/docker-ubuntu2404-ansible:latest
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    tmpfs:
      - /tmp
      - /run

  - name: yugabyte-ubuntu2204
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run

  - name: yugabyte-rhel9
    image: geerlingguy/docker-rockylinux9-ansible:latest
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run

  - name: yugabyte-rhel10
    image: geerlingguy/docker-rockylinux9-ansible:latest  # use closest available
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run

provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp/.ansible/tmp
      interpreter_python: auto_silent
  inventory:
    host_vars:
      yugabyte-ubuntu2404:
        ansible_python_interpreter: /usr/bin/python3
      yugabyte-ubuntu2204:
        ansible_python_interpreter: /usr/bin/python3
      yugabyte-rhel9:
        ansible_python_interpreter: /usr/bin/python3
      yugabyte-rhel10:
        ansible_python_interpreter: /usr/bin/python3

verifier:
  name: ansible