---
galaxy_info:
  role_name: yugabyte_configure
  author: YugabyteDB Ansible Collection Contributors
  description: Configures YugabyteDB master and tserver processes
  license: Apache-2.0
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions: ["8", "9", "10"]
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions: ["jammy", "noble"]
dependencies:
  - role: mahadzar81.yugabytedb_collection.yugabyte_install
